DEBUG = True
PORT = 8080
HOST = '127.0.0.1'
DB_NAME = 'journal.db'
SECRET_KEY = 'rfWF1AKPS8qpJoQ3iLoG6J0bGGDAZ9Yd'

DEFAULT_USER = 'admin'
DEFAULT_USER_PASSWORD = 'password'
DEFAULT_USER_EMAIL = 'admin@test.com'
